name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: set image version
        id: image-version
        run: echo "gitsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build the docker image
        run: docker build . --file Dockerfile --tag ghcr.io/isracoder/express-docker-fork:${{ steps.image-version.outputs.gitsha }}
      - name: Publish docker image
        run: docker push ghcr.io/isracoder/express-docker-fork:${{ steps.image-version.outputs.gitsha }}
